# Available Agents

> Auto-generated catalog. Do not edit manually.
> Generated by: scripts/generate-agents-catalog.sh

## General

| Agent | Description |
|-------|-------------|
| orchestrator | Master orchestrator that coordinates multiple sub-agents for complex multi-domain tasks |

## Business

| Agent | Description |
|-------|-------------|
| api-designer | API design expert specializing in REST, GraphQL, OpenAPI specifications, and API-first development |
| business-analyst | Business analysis expert specializing in process optimization, workflow design, gap analysis, and business transformation |
| product-strategist | Product strategy expert for market analysis, feature prioritization, and product roadmapping |
| project-manager | Project management expert for sprint planning, task coordination, and team collaboration |
| requirements-analyst | Requirements engineering specialist for gathering, analyzing, and documenting system requirements and user stories |
| technical-writer | Technical writing expert specializing in documentation, user guides, tutorials, and comprehensive technical content |

## Creative

| Agent | Description |
|-------|-------------|
| ux-designer | UX/UI design expert for user research, wireframing, and design systems |

## Data Ai

| Agent | Description |
|-------|-------------|
| ai-engineer | AI/ML specialist for LLMs, computer vision, NLP, and production ML systems. |
| analytics-engineer | Analytics engineering expert specializing in dbt, data modeling, BI tools, and modern data stack architecture |
| data-engineer | Data engineering expert for ETL pipelines, data warehouses, and big data processing |
| data-scientist | Data science expert specializing in statistical analysis, machine learning, data visualization, and experimental design |
| mlops-engineer | MLOps expert specializing in ML pipeline automation, model deployment, experiment tracking, and production ML systems |
| prompt-engineer | Prompt engineering specialist focusing on LLM optimization, RAG systems, fine-tuning, and advanced AI application development |

## Development

| Agent | Description |
|-------|-------------|
| angular-expert | Angular 17+ expert for standalone components, signals, RxJS, and enterprise applications |
| backend-architect | Expert in backend architecture, API design, microservices, and database schemas |
| database-specialist | Database design, optimization, and management expert for SQL and NoSQL systems |
| frontend-specialist | Expert in modern frontend development, React, Vue, Angular, and UI/UX implementation. |
| fullstack-engineer | Full-stack development expert capable of building complete applications from frontend to backend |
| golang-pro | Go language expert for concurrent programming, microservices, and cloud-native development |
| java-enterprise | Java expert for enterprise applications, Spring Boot, microservices, and JVM optimization |
| javascript-pro | JavaScript expert for modern ES6+, async programming, performance optimization, and Node.js |
| nextjs-pro | Next.js 14+ expert for App Router, React Server Components, ISR, and full-stack development |
| python-pro | Python expert specializing in advanced features, async programming, and performance optimization. |
| react-pro | React expert for advanced hooks, performance optimization, state management, and modern patterns |
| rust-pro | Rust systems programming expert for memory safety, performance optimization, and concurrent programming |
| spring-boot-4-expert | Especialista en Spring Boot 4.0, Jakarta EE 10, Java 21+. Migraciones, nuevas features, best practices. |
| typescript-pro | TypeScript expert for advanced type systems, large-scale applications, and type-safe development |
| vue-specialist | Vue.js 3 expert for Composition API, Nuxt 3, Pinia, and reactive programming |

## Infrastructure

| Agent | Description |
|-------|-------------|
| cloud-architect | Cloud architecture expert for AWS, GCP, and Azure with focus on scalable, cost-effective solutions. |
| deployment-manager | Release orchestration expert specializing in deployment strategies, rollback procedures, and production reliability |
| devops-engineer | DevOps and infrastructure expert specializing in CI/CD pipelines, containerization, |
| incident-responder | Production incident response expert for debugging, log analysis, root cause analysis, and system recovery |
| kubernetes-expert | Kubernetes specialist focusing on cluster management, workload orchestration, and cloud-native architectures |
| monitoring-specialist | Observability expert for metrics, logs, traces, alerting, and comprehensive system monitoring |
| performance-engineer | Performance optimization expert for profiling, load testing, bottleneck analysis, and system tuning |

## Quality

| Agent | Description |
|-------|-------------|
| accessibility-auditor | Accessibility expert specializing in WCAG compliance, screen reader testing, and inclusive design practices |
| code-reviewer | Expert code reviewer focusing on quality, security, performance, and best practices. |
| code-reviewer-compact | Reviewer compacto con checklist de calidad, seguridad y convenciones. |
| dependency-manager | Expert in dependency management, security auditing, version optimization, and license compliance |
| e2e-test-specialist | End-to-end testing expert specializing in Playwright, Cypress, test automation, and comprehensive testing strategies |
| performance-tester | Performance testing expert specializing in load testing, stress testing, benchmarking, and performance optimization |
| security-auditor | Security specialist for vulnerability assessment, penetration testing, and compliance auditing |
| test-engineer | Testing expert for unit, integration, E2E testing, and test automation strategies. |

## Specialized

| Agent | Description |
|-------|-------------|
| agent-generator | Dynamic agent creation specialist for generating custom agents based on requirements and patterns |
| blockchain-developer | Blockchain and Web3 expert for smart contracts, DeFi, and decentralized applications |
| code-migrator | Expert in code migrations, framework upgrades, and technology transitions with safe, incremental approaches |
| context-manager | Advanced session continuity, memory management, context preservation, and intelligent state handling |
| documentation-writer | Automated documentation specialist for technical writing, API docs, user guides, and comprehensive documentation |
| ecommerce-expert | E-commerce platform specialist, shopping cart systems, payment integration, inventory management, order fulfillment |
| embedded-engineer | IoT specialist, embedded systems expert, Arduino and Raspberry Pi developer, real-time systems, hardware interfaces |
| error-detective | Advanced debugging specialist for root cause analysis, error pattern detection, and intelligent troubleshooting |
| fintech-specialist | Financial technology expert, payment systems architect, compliance and security specialist, blockchain and crypto |
| freelance-project-planner | Especialista en análisis de proyectos existentes y creación de planificación iterativa usando metodología híbrida Kanban + XP para desarrolladores freelance |
| freelance-project-planner-v2 | Especialista en análisis de proyectos existentes con integración GitHub MCP para automatización completa |
| freelance-project-planner-v3 | Especialista en planificación freelance con Docker y CI/CD desde el inicio, aprendizaje progresivo integrado |
| freelance-project-planner-v4 | Agente completo para planificación freelance multi-lenguaje con GitFlow, Stacked PRs, y Preview Environments |
| game-developer | Game development specialist for Unity, Unreal Engine, game mechanics, physics, and multiplayer systems |
| healthcare-dev | Healthcare technology specialist, HIPAA compliance expert, HL7/FHIR standards, medical device integration, EHR/EMR systems |
| mobile-developer | Mobile app development expert for iOS, Android, and cross-platform solutions |
| parallel-plan-executor | Parallel execution orchestrator that launches multiple plan-executor agents concurrently for maximum parallelization |
| plan-executor | Autonomous execution orchestrator for implementation plans with VibeKanban integration |
| solo-dev-planner | Agente modular para solo developers. Carga módulos según necesidad. Setup en 15 min, deploy global, auto-fix de errores. |
| solo-dev-planner | Agente optimizado para solo developers. Modular: carga solo lo que necesitas. Filosofía Speedrun con Atomic Sequential Merges. Production-ready desde día 1. |
| solo-dev-planner-core | Módulo Core: Filosofía y Workflow principal del Solo Dev Planner |
| solo-dev-planner-deployment | Módulo 4: Deploy con Koyeb, Railway, Coolify |
| solo-dev-planner-install | Guía de instalación del Solo Dev Planner |
| solo-dev-planner-operations | Módulo 6: DB Migrations, Secrets, Monitoring, Mise |
| solo-dev-planner-progressive-setup | Módulo 3: Setup en 3 fases (MVP, Alpha, Beta) |
| solo-dev-planner-readme | README del Solo Dev Planner - Guía de estructura modular |
| solo-dev-planner-self-correction | Módulo 2: Auto-fix y context management |
| solo-dev-planner-start | Punto de inicio del Solo Dev Planner |
| solo-dev-planner-testing | Módulo 5: Testing robusto con Testcontainers |
| solo-dev-planner-workflow | Diagrama de flujo del Solo Dev Planner |
| template-writer | Especialista en templates Mustache para generación de código. Sintaxis, contextos, partials. |
| test-runner | Ejecuta tests y analiza resultados. |
| vibekanban-smart-worker | Intelligent vibekanban task executor that automatically selects the optimal Claude model based on task type |
| wave-executor | Ejecuta tareas de una oleada en paralelo o secuencial. |
| workflow-optimizer | Process improvement specialist focusing on automation, optimization, CI/CD pipelines, and workflow efficiency |

