# ===========================================
# GitLab CI for Node.js Projects
# ===========================================
# Copy to: .gitlab-ci.yml
#
# MINIMAL CI - runs only on tags and manual triggers.
# Run full validation locally: ./.ci-local/ci-local.sh full
# ===========================================

image: node:20-alpine  # Change: 18, 20, 22

stages:
  - build
  - docker

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - node_modules/
    - .npm/

# ===========================================
# BUILD - Only on tags or manual
# ===========================================
build:
  stage: build
  script:
    - npm ci
    - npm run lint || true
    - npm run build
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/
    - when: manual
      allow_failure: true

# ===========================================
# DOCKER - Only on version tags
# ===========================================
# docker:
#   stage: docker
#   image: docker:latest
#   services:
#     - docker:dind
#   script:
#     - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
#     - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
#   rules:
#     - if: $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/
