# =============================================================================
# GitLab CI - Python Project
# =============================================================================
# Minimal CI for Python projects. Copy to your project as .gitlab-ci.yml
#
# Features:
#   - Build verification only (tests run locally via CI-Local)
#   - Manual trigger, merge request, or tag-based releases
#   - Supports pip, poetry, and uv
# =============================================================================

image: python:3.12-slim

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"
  POETRY_HOME: "$CI_PROJECT_DIR/.poetry"
  POETRY_VIRTUALENVS_IN_PROJECT: "true"

stages:
  - build
  - publish

# Cache pip/poetry dependencies
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .pip-cache/
    - .venv/
    - .poetry/

# =============================================================================
# Lint with pip - Reports failures without blocking pipeline
# =============================================================================
lint-pip:
  stage: build
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && ($PACKAGE_MANAGER == "pip" || $PACKAGE_MANAGER == null)
    - if: $CI_COMMIT_TAG && ($PACKAGE_MANAGER == "pip" || $PACKAGE_MANAGER == null)
    - if: ($PACKAGE_MANAGER == "pip" || $PACKAGE_MANAGER == null)
      when: manual
      allow_failure: true
  script:
    - python -m pip install --upgrade pip
    - pip install ruff mypy
    - ruff check .
    - mypy . --ignore-missing-imports

# =============================================================================
# Build with pip
# =============================================================================
build-pip:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && ($PACKAGE_MANAGER == "pip" || $PACKAGE_MANAGER == null)
    - if: $CI_COMMIT_TAG && ($PACKAGE_MANAGER == "pip" || $PACKAGE_MANAGER == null)
    - if: ($PACKAGE_MANAGER == "pip" || $PACKAGE_MANAGER == null)
      when: manual
      allow_failure: true
  script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt || true
    - pip install -r requirements-dev.txt || true

# =============================================================================
# Lint with Poetry - Reports failures without blocking pipeline
# =============================================================================
lint-poetry:
  stage: build
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PACKAGE_MANAGER == "poetry"
    - if: $CI_COMMIT_TAG && $PACKAGE_MANAGER == "poetry"
    - if: $PACKAGE_MANAGER == "poetry"
      when: manual
      allow_failure: true
  before_script:
    - pip install poetry
    - export PATH="$POETRY_HOME/bin:$PATH"
  script:
    - poetry install
    - poetry run ruff check .
    - poetry run mypy . --ignore-missing-imports

# =============================================================================
# Build with Poetry
# =============================================================================
build-poetry:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PACKAGE_MANAGER == "poetry"
    - if: $CI_COMMIT_TAG && $PACKAGE_MANAGER == "poetry"
    - if: $PACKAGE_MANAGER == "poetry"
      when: manual
      allow_failure: true
  before_script:
    - pip install poetry
    - export PATH="$POETRY_HOME/bin:$PATH"
  script:
    - poetry install

# =============================================================================
# Lint with uv - Reports failures without blocking pipeline
# =============================================================================
lint-uv:
  stage: build
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PACKAGE_MANAGER == "uv"
    - if: $CI_COMMIT_TAG && $PACKAGE_MANAGER == "uv"
    - if: $PACKAGE_MANAGER == "uv"
      when: manual
      allow_failure: true
  before_script:
    - pip install uv
  script:
    - uv sync
    - uv run ruff check .
    - uv run mypy . --ignore-missing-imports

# =============================================================================
# Build with uv
# =============================================================================
build-uv:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $PACKAGE_MANAGER == "uv"
    - if: $CI_COMMIT_TAG && $PACKAGE_MANAGER == "uv"
    - if: $PACKAGE_MANAGER == "uv"
      when: manual
      allow_failure: true
  before_script:
    - pip install uv
  script:
    - uv sync

# =============================================================================
# Publish to PyPI - Only on version tags
# =============================================================================
# publish:
#   stage: publish
#   rules:
#     - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
#   script:
#     - pip install build twine
#     - python -m build
#     - twine upload dist/* -u __token__ -p $PYPI_TOKEN
