# =============================================================================
# CI Monorepo - GitHub Actions
# =============================================================================
# Template para monorepos con multiple servicios/packages
# Copia este archivo a tu proyecto: .github/workflows/ci.yml
# =============================================================================

name: CI Monorepo

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.gitignore'
  pull_request:
    branches: [main, develop]
    paths-ignore:
      - '**.md'
      - '.gitignore'
  workflow_dispatch:
    inputs:
      service:
        description: 'Service to build (all = todos)'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - frontend
          - backend
          - shared

permissions:
  contents: read

# Cancelar runs anteriores del mismo PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # =========================================================================
  # Detectar cambios por directorio
  # =========================================================================
  changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
      shared: ${{ steps.filter.outputs.shared }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'packages/frontend/**'
              - 'apps/web/**'
            backend:
              - 'packages/backend/**'
              - 'apps/api/**'
              - 'services/**'
            shared:
              - 'packages/shared/**'
              - 'libs/**'

  # =========================================================================
  # Build Frontend (Node.js)
  # =========================================================================
  frontend:
    needs: changes
    if: |
      needs.changes.outputs.frontend == 'true' ||
      needs.changes.outputs.shared == 'true' ||
      github.event.inputs.service == 'all' ||
      github.event.inputs.service == 'frontend'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/frontend  # Ajustar segun tu estructura
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: packages/frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Build
        run: npm run build

  # =========================================================================
  # Build Backend (ejemplo Java)
  # =========================================================================
  backend:
    needs: changes
    if: |
      needs.changes.outputs.backend == 'true' ||
      needs.changes.outputs.shared == 'true' ||
      github.event.inputs.service == 'all' ||
      github.event.inputs.service == 'backend'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/backend  # Ajustar segun tu estructura
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew build -x test

  # =========================================================================
  # Summary
  # =========================================================================
  summary:
    needs: [frontend, backend]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check results
        env:
          FRONTEND_RESULT: ${{ needs.frontend.result }}
          BACKEND_RESULT: ${{ needs.backend.result }}
        run: |
          echo "Frontend: $FRONTEND_RESULT"
          echo "Backend: $BACKEND_RESULT"

          if [[ "$FRONTEND_RESULT" == "failure" ]] || \
             [[ "$BACKEND_RESULT" == "failure" ]]; then
            echo "::error::One or more jobs failed"
            exit 1
          fi
