# ===========================================
# CI for Rust Projects
# ===========================================
# Copy to: .github/workflows/ci.yml
# ===========================================

name: CI

on:
  pull_request:
    branches: [main, develop]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:
    inputs:
      run_tests:
        description: 'Run tests'
        default: false
        type: boolean

jobs:
  build:
    uses: JNZader/project-starter-framework/.github/workflows/reusable-build-rust.yml@main
    with:
      toolchain: 'stable'  # Change to: stable, beta, nightly
      run-clippy: true
      run-fmt: true
      run-tests: ${{ github.event.inputs.run_tests == 'true' }}
